apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: totem-express-payments-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: totem-express-payments-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50