apiVersion: v1
kind: Service
metadata:
  name: totem-express-payments-service
spec:
  selector:
    app: totem-express-payments-service
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  type: LoadBalancer